#!/bin/bash

#ddev-generated
## Command provided by https://github.com/weitzman/ddev-drupal-gitlabci
## Description: Run eslint inside the web container
## Usage: eslint [flags] [args]
## Example: "ddev eslint"
## ProjectTypes: drupal8,drupal9,drupal10
## ExecRaw: true

if yarn --cwd $DDEV_DOCROOT/core eslint --version >/dev/null ; then
  yarn --cwd $DDEV_DOCROOT/core --config .eslintrc.legacy.json eslint ../modules/custom/**/*.js "$@"
else
  echo "eslint is not available. You may need to 'ddev yarn --cwd $DDEV_DOCROOT/core install'"
  exit 1
fi

