#!/bin/bash

#ddev-generated
## Command provided by https://github.com/ddev/ddev-drupal-contrib
## Description: Run eslint inside the web container
## Usage: eslint [flags] [args]
## Example: "ddev eslint"
## ProjectTypes: drupal8,drupal9,drupal10
## ExecRaw: true

if "$DDEV_DOCROOT/core/node_modules/.bin/eslint" --version >/dev/null ; then
  "$DDEV_DOCROOT/core/node_modules/.bin/eslint" --no-error-on-unmatched-pattern --ignore-pattern "*.es6.js" --config "$DDEV_DOCROOT/core/.eslintrc.legacy.json" --resolve-plugins-relative-to "$DDEV_DOCROOT/core" "$DDEV_DOCROOT/modules/custom/**/*.js"
else
  echo "eslint is not available. You may need to 'ddev yarn --cwd $DDEV_DOCROOT/core install'"
  exit 1
fi
