#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/ddev/ddev-drupal-contrib
## Description: Symlink project files into the configured location (defaults to `web/modules/custom/[PROJECT_NAME]`)
## Usage: symlink-project [flags] [args]
## Example: "ddev symlink-project"
## ExecRaw: true

set -eu -o pipefail

export _WEB_ROOT=$DDEV_DOCROOT
cd "$DDEV_COMPOSER_ROOT" || exit
curl -OL https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/scripts/symlink_project.php

# Suppress a warning from symlink_project.php about the list of project files
# and folders being derived, because the environment variable PROJECT_FILES is
# empty.
if [ -z "${PROJECT_FILES-}" ]; then
  # Build the list of files to symlink by filtering out those excluded via
  # .gitattributes export-ignore and a few common, hardcoded values.
  FILTERED_PROJECT_FILES=()
  for f in * .*; do
    [[ "$f" == .* ]] && continue
    case "$f" in
      web|docroot|vendor|symlink_project.php|.ddev|.idea) continue ;;
    esac
    if git check-attr export-ignore "$f" 2>/dev/null | grep -q 'export-ignore: set'; then
      continue
    fi
    FILTERED_PROJECT_FILES+=("$f")
  done
  PROJECT_FILES="$(printf '%s\n' "${FILTERED_PROJECT_FILES[@]}")"
  export PROJECT_FILES
fi

# Symlink name using underscores.
# @see https://www.drupal.org/docs/develop/creating-modules/naming-and-placing-your-drupal-module
# DRUPAL_PROJECT_FOLDER is used by the symlink-project script in gitlab_templates
export DRUPAL_PROJECT_FOLDER=${DDEV_DOCROOT}/${DRUPAL_PROJECTS_PATH}/${DDEV_SITENAME//-/_}
php symlink_project.php
rm -f symlink_project.php
